name = "hono-src"
compatibility_date = "2024-09-09"

# Uncomment the next line if you need Node.js compatibility
# compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmM0NGFhNzktMWYzZC00NmViLTliYmEtNjhiZWEyZDZiZTQ3IiwidGVuYW50X2lkIjoiMmE4NGZjYmFlOTZjOTYxOGEyYzkxYzNmNzYwZjVmYTczMDFiZWI5YmUzMjAyMmUxMDQ3ZmQ3ZWQ5MGUyM2Q5MCIsImludGVybmFsX3NlY3JldCI6ImM3MTUzY2EwLTkzOTAtNDI0My1iZDk3LTdkYjdhODA1OWNiMyJ9.8tOohXJX9WwBN5hfjAjlBc8idITNZbBADNEPeWJjk2M"
SECRET_KEY = "thisismysecretkeyitshouldntmakeSenseNowShallIt"